pipeline {
    agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: docker
    image: docker:24-dind
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""
  - name: jnlp
    image: jenkins/inbound-agent:latest
"""
        }
    }
    environment {
        IMAGE_NAME = "fstathios/myapp"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    stages {
        stage('Clone Repo') {
            steps {
                git url: 'https://github.com/Fstathios/lab.git', branch: 'main'
            }
        }
        stage('Install kubectl') {
            steps {
                container('docker') {
                    sh '''
                        wget -O kubectl "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl"
                        chmod +x kubectl
                        mv kubectl /usr/local/bin/kubectl
                    '''
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                container('docker') {
                    sh 'docker build -t $IMAGE_NAME:$IMAGE_TAG Kubernetes/newapp/'
                }
            }
        }
        stage('Push to Docker Hub') {
            steps {
                container('docker') {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                        sh 'docker push $IMAGE_NAME:$IMAGE_TAG'
                    }
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                container('docker') {
                    sh 'kubectl apply -f Kubernetes/newapp/ -n vote-app'
                }
            }
        }
        stage('Verify Deployment') {
            steps {
                container('docker') {
                    sh 'kubectl get pods -n vote-app'
                }
            }
        }
    }
    post {
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
}
