pipeline {
    agent any
    stages {
        stage('Clone Repo') {
            steps {
                git url: 'https://github.com/Fstathios/lab.git', branch: 'main'
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f Kubernetes/newapp/ -n vote-app'
            }
        }
        stage('Verify Deployment') {
            steps {
                sh 'kubectl get pods -n vote-app'
            }
        }
    }
    post {
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
}
