apiVersion: v1
kind: Pod
metadata:
  labels:
    run: soxos
  name: soxos
spec:
  containers:
  - image: ngnix
    name: soxos
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
